version: '3'
services:
  server:
    build:
      context: ./salamantex-coding-challenge-server/
    ports:
      - "4000:4000"
  client:
    build:
      context: ./salamantex-coding-challenge-client/
    depends_on:
      - server
    ports:
      - "3000:80"